import { Flight, Hotel, Destination, PriceTrend, Train, RailPass, Activity, Restaurant } from '@/types';

// Mock flight data
export const mockFlights: Flight[] = [
  {
    id: 'FL001',
    airline: 'United Airlines',
    flightNumber: 'UA889',
    origin: 'SFO',
    destination: 'NRT',
    departure: new Date('2025-12-15T10:30:00'),
    arrival: new Date('2025-12-16T14:45:00'),
    duration: 675,
    price: 850,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.2,
    onTimePerformance: 82,
    carbonEmission: 920,
  },
  {
    id: 'FL002',
    airline: 'ANA',
    flightNumber: 'NH7',
    origin: 'SFO',
    destination: 'NRT',
    departure: new Date('2025-12-15T11:00:00'),
    arrival: new Date('2025-12-16T15:30:00'),
    duration: 690,
    price: 920,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.5,
    onTimePerformance: 89,
    carbonEmission: 900,
  },
  {
    id: 'FL003',
    airline: 'Delta',
    flightNumber: 'DL283',
    origin: 'LAX',
    destination: 'CDG',
    departure: new Date('2025-12-20T18:00:00'),
    arrival: new Date('2025-12-21T14:30:00'),
    duration: 630,
    price: 1200,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.3,
    onTimePerformance: 85,
    carbonEmission: 1050,
  },
  {
    id: 'FL004',
    airline: 'Emirates',
    flightNumber: 'EK215',
    origin: 'JFK',
    destination: 'DXB',
    departure: new Date('2025-12-18T22:30:00'),
    arrival: new Date('2025-12-19T19:45:00'),
    duration: 795,
    price: 1450,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.8,
    onTimePerformance: 91,
    carbonEmission: 1200,
  },
  {
    id: 'FL005',
    airline: 'Singapore Airlines',
    flightNumber: 'SQ12',
    origin: 'LAX',
    destination: 'SIN',
    departure: new Date('2025-12-22T00:30:00'),
    arrival: new Date('2025-12-23T07:15:00'),
    duration: 945,
    price: 1350,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.9,
    onTimePerformance: 92,
    carbonEmission: 1400,
  },
  {
    id: 'FL006',
    airline: 'British Airways',
    flightNumber: 'BA283',
    origin: 'JFK',
    destination: 'LHR',
    departure: new Date('2025-12-16T21:00:00'),
    arrival: new Date('2025-12-17T09:30:00'),
    duration: 450,
    price: 950,
    currency: 'USD',
    stops: 0,
    cabinClass: 'premium-economy',
    rating: 4.1,
    onTimePerformance: 79,
    carbonEmission: 850,
  },
  {
    id: 'FL007',
    airline: 'Lufthansa',
    flightNumber: 'LH400',
    origin: 'JFK',
    destination: 'FRA',
    departure: new Date('2025-12-19T17:45:00'),
    arrival: new Date('2025-12-20T07:20:00'),
    duration: 455,
    price: 880,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.3,
    onTimePerformance: 86,
    carbonEmission: 870,
  },
  {
    id: 'FL008',
    airline: 'Qatar Airways',
    flightNumber: 'QR701',
    origin: 'LAX',
    destination: 'DOH',
    departure: new Date('2025-12-21T15:20:00'),
    arrival: new Date('2025-12-22T21:30:00'),
    duration: 850,
    price: 1280,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.7,
    onTimePerformance: 88,
    carbonEmission: 1300,
  },
];

// Mock hotel data
export const mockHotels: Hotel[] = [
  {
    id: 'HT001',
    name: 'Grand Hyatt Tokyo',
    address: '6-10-3 Roppongi, Minato-ku',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.5,
    stars: 5,
    price: 280,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Room Service'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa'],
    distanceToCenter: 2.5,
    reviewScore: 8.9,
    reviewCount: 3420,
  },
  {
    id: 'HT002',
    name: 'Hotel Gracery Shinjuku',
    address: '1-19-1 Kabukicho, Shinjuku-ku',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.2,
    stars: 4,
    price: 180,
    currency: 'USD',
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    distanceToCenter: 1.2,
    reviewScore: 8.5,
    reviewCount: 2156,
  },
  {
    id: 'HT003',
    name: 'Hôtel Plaza Athénée',
    address: '25 Avenue Montaigne',
    city: 'Paris',
    country: 'France',
    rating: 4.8,
    stars: 5,
    price: 950,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Butler Service', 'Michelin Restaurant'],
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb'],
    distanceToCenter: 0.8,
    reviewScore: 9.4,
    reviewCount: 1876,
  },
  {
    id: 'HT004',
    name: 'Generator Paris',
    address: '9-11 Place du Colonel Fabien',
    city: 'Paris',
    country: 'France',
    rating: 3.9,
    stars: 3,
    price: 85,
    currency: 'USD',
    amenities: ['WiFi', 'Bar', 'Terrace', 'Lounge'],
    images: ['https://images.unsplash.com/photo-1455587734955-081b22074882'],
    distanceToCenter: 3.5,
    reviewScore: 7.8,
    reviewCount: 892,
  },
  {
    id: 'HT005',
    name: 'Marina Bay Sands',
    address: '10 Bayfront Avenue',
    city: 'Singapore',
    country: 'Singapore',
    rating: 4.7,
    stars: 5,
    price: 420,
    currency: 'USD',
    amenities: ['WiFi', 'Infinity Pool', 'Casino', 'Gym', 'Spa', 'Shopping Mall', 'Rooftop Bar'],
    images: ['https://images.unsplash.com/photo-1525438160292-a4a860951216'],
    distanceToCenter: 1.5,
    reviewScore: 9.1,
    reviewCount: 5230,
  },
  {
    id: 'HT006',
    name: 'The Ritz-Carlton New York',
    address: 'Central Park, 50 Central Park South',
    city: 'New York',
    country: 'USA',
    rating: 4.8,
    stars: 5,
    price: 650,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Concierge', 'Central Park View'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    distanceToCenter: 0.5,
    reviewScore: 9.3,
    reviewCount: 4120,
  },
  {
    id: 'HT007',
    name: 'Burj Al Arab',
    address: 'Jumeirah Beach Road',
    city: 'Dubai',
    country: 'UAE',
    rating: 5.0,
    stars: 5,
    price: 1500,
    currency: 'USD',
    amenities: ['WiFi', 'Private Beach', 'Butler Service', 'Helipad', 'Spa', 'Fine Dining', 'Gold Plated Fixtures'],
    images: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c'],
    distanceToCenter: 8.0,
    reviewScore: 9.7,
    reviewCount: 6890,
  },
  {
    id: 'HT008',
    name: 'W Barcelona',
    address: 'Placa de la Rosa dels Vents 1',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.5,
    stars: 5,
    price: 320,
    currency: 'USD',
    amenities: ['WiFi', 'Beachfront', 'Pool', 'Gym', 'Restaurant', 'Nightclub', 'Spa'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'],
    distanceToCenter: 3.2,
    reviewScore: 8.8,
    reviewCount: 3456,
  },
];

// Mock destination data
export const mockDestinations: Destination[] = [
  {
    id: 'DEST001',
    name: 'Tokyo',
    country: 'Japan',
    description: 'A vibrant metropolis blending traditional culture with cutting-edge technology',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf',
    popularityScore: 9.5,
    averageTemperature: 16,
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
  },
  {
    id: 'DEST002',
    name: 'Paris',
    country: 'France',
    description: 'The City of Light, famous for art, fashion, gastronomy, and culture',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34',
    popularityScore: 9.7,
    averageTemperature: 12,
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST003',
    name: 'Bali',
    country: 'Indonesia',
    description: 'Tropical paradise with stunning beaches, rice terraces, and spiritual culture',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
    popularityScore: 9.2,
    averageTemperature: 27,
    bestMonths: ['April', 'May', 'June', 'July', 'August', 'September'],
  },
  {
    id: 'DEST004',
    name: 'New York',
    country: 'USA',
    description: 'The city that never sleeps, offering world-class dining, shopping, and entertainment',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9',
    popularityScore: 9.6,
    averageTemperature: 13,
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST005',
    name: 'Dubai',
    country: 'UAE',
    description: 'Futuristic city with luxury shopping, ultramodern architecture, and desert adventures',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
    popularityScore: 9.0,
    averageTemperature: 27,
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
  },
  {
    id: 'DEST006',
    name: 'Barcelona',
    country: 'Spain',
    description: 'Mediterranean gem with stunning architecture, beaches, and vibrant culture',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded',
    popularityScore: 9.3,
    averageTemperature: 16,
    bestMonths: ['May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST007',
    name: 'Singapore',
    country: 'Singapore',
    description: 'Modern city-state with futuristic gardens, diverse cuisine, and world-class shopping',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
    popularityScore: 9.4,
    averageTemperature: 28,
    bestMonths: ['February', 'March', 'April', 'July', 'August'],
  },
  {
    id: 'DEST008',
    name: 'London',
    country: 'United Kingdom',
    description: 'Historic capital with royal palaces, world-class museums, and multicultural neighborhoods',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
    popularityScore: 9.5,
    averageTemperature: 11,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
  },
  {
    id: 'DEST009',
    name: 'Iceland',
    country: 'Iceland',
    description: 'Land of fire and ice with stunning waterfalls, glaciers, and Northern Lights',
    imageUrl: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927',
    popularityScore: 8.9,
    averageTemperature: 5,
    bestMonths: ['June', 'July', 'August', 'September'],
  },
];

// Mock price trend data generator
export const generatePriceTrend = (basePrice: number, days: number = 30): PriceTrend[] => {
  const trends: PriceTrend[] = [];
  const today = new Date();

  for (let i = -days; i <= 30; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() + i);

    // Create realistic price fluctuation
    const variance = Math.sin(i / 7) * 100 + Math.random() * 80;
    const price = Math.round(basePrice + variance);

    trends.push({
      date: date.toISOString().split('T')[0],
      price,
      prediction: i > 0,
    });
  }

  return trends;
};

// Helper function to search flights
export const searchFlights = (origin?: string, destination?: string): Flight[] => {
  return mockFlights.filter(flight => {
    if (origin && !flight.origin.toLowerCase().includes(origin.toLowerCase())) return false;
    if (destination && !flight.destination.toLowerCase().includes(destination.toLowerCase())) return false;
    return true;
  });
};

// Helper function to search hotels
export const searchHotels = (city?: string, maxPrice?: number): Hotel[] => {
  return mockHotels.filter(hotel => {
    if (city && !hotel.city.toLowerCase().includes(city.toLowerCase())) return false;
    if (maxPrice && hotel.price > maxPrice) return false;
    return true;
  });
};

// Mock train data
export const mockTrains: Train[] = [
  {
    id: 'TR001',
    operator: 'JR East',
    trainNumber: 'Nozomi 1',
    trainType: 'Shinkansen (Bullet Train)',
    origin: 'Tokyo',
    destination: 'Osaka',
    departure: new Date('2025-12-15T09:00:00'),
    arrival: new Date('2025-12-15T11:30:00'),
    duration: 150,
    price: 135,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Vending Machines', 'Spacious Seats'],
    seatAvailability: { window: 12, aisle: 8, total: 20 },
    rating: 4.9,
    onTimePerformance: 99,
    carbonEmission: 18,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR002',
    operator: 'SNCF',
    trainNumber: 'TGV 6821',
    trainType: 'TGV (High Speed)',
    origin: 'Paris',
    destination: 'Lyon',
    departure: new Date('2025-12-16T07:30:00'),
    arrival: new Date('2025-12-16T09:28:00'),
    duration: 118,
    price: 65,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Café Car', 'Air Conditioning'],
    seatAvailability: { window: 15, aisle: 10, total: 25 },
    rating: 4.6,
    onTimePerformance: 88,
    carbonEmission: 14,
    flexibleTicket: false,
    refundable: false,
  },
  {
    id: 'TR003',
    operator: 'DB (Deutsche Bahn)',
    trainNumber: 'ICE 71',
    trainType: 'ICE (InterCity Express)',
    origin: 'Berlin',
    destination: 'Munich',
    departure: new Date('2025-12-17T10:15:00'),
    arrival: new Date('2025-12-17T14:30:00'),
    duration: 255,
    price: 89,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Restaurant Car', 'Quiet Zone', 'Reclining Seats'],
    seatAvailability: { window: 8, aisle: 5, total: 13 },
    rating: 4.7,
    onTimePerformance: 82,
    carbonEmission: 22,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR004',
    operator: 'Trenitalia',
    trainNumber: 'Frecciarossa 9320',
    trainType: 'Frecciarossa (Red Arrow)',
    origin: 'Rome',
    destination: 'Milan',
    departure: new Date('2025-12-18T14:00:00'),
    arrival: new Date('2025-12-18T17:10:00'),
    duration: 190,
    price: 75,
    currency: 'USD',
    class: 'business',
    amenities: ['WiFi', 'Power Outlets', 'Complimentary Snacks', 'Extra Legroom'],
    seatAvailability: { window: 6, aisle: 4, total: 10 },
    rating: 4.5,
    onTimePerformance: 85,
    carbonEmission: 16,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR005',
    operator: 'Renfe',
    trainNumber: 'AVE 03050',
    trainType: 'AVE (Alta Velocidad Española)',
    origin: 'Madrid',
    destination: 'Barcelona',
    departure: new Date('2025-12-19T08:00:00'),
    arrival: new Date('2025-12-19T10:45:00'),
    duration: 165,
    price: 68,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Snack Service'],
    seatAvailability: { window: 18, aisle: 12, total: 30 },
    rating: 4.4,
    onTimePerformance: 90,
    carbonEmission: 15,
    flexibleTicket: false,
    refundable: false,
  },
  {
    id: 'TR006',
    operator: 'SBB',
    trainNumber: 'IC 715',
    trainType: 'InterCity',
    origin: 'Zurich',
    destination: 'Geneva',
    departure: new Date('2025-12-20T11:30:00'),
    arrival: new Date('2025-12-20T14:25:00'),
    duration: 175,
    price: 95,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Dining Car', 'Panoramic Windows'],
    seatAvailability: { window: 10, aisle: 6, total: 16 },
    rating: 4.8,
    onTimePerformance: 95,
    carbonEmission: 12,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR007',
    operator: 'Amtrak',
    trainNumber: 'Acela 2150',
    trainType: 'Acela Express',
    origin: 'New York',
    destination: 'Washington DC',
    departure: new Date('2025-12-21T15:00:00'),
    arrival: new Date('2025-12-21T18:00:00'),
    duration: 180,
    price: 125,
    currency: 'USD',
    class: 'business',
    amenities: ['WiFi', 'Power Outlets', 'Café Car', 'Conference Tables'],
    seatAvailability: { window: 14, aisle: 9, total: 23 },
    rating: 4.2,
    onTimePerformance: 78,
    carbonEmission: 25,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR008',
    operator: 'JR West',
    trainNumber: 'Hikari 522',
    trainType: 'Shinkansen',
    origin: 'Kyoto',
    destination: 'Hiroshima',
    departure: new Date('2025-12-22T12:00:00'),
    arrival: new Date('2025-12-22T13:48:00'),
    duration: 108,
    price: 115,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Extra Wide Seats', 'Luggage Space'],
    seatAvailability: { window: 7, aisle: 5, total: 12 },
    rating: 4.9,
    onTimePerformance: 98,
    carbonEmission: 15,
    flexibleTicket: true,
    refundable: true,
  },
];

// Mock rail pass data
export const mockRailPasses: RailPass[] = [
  {
    id: 'RP001',
    name: 'Eurail Global Pass',
    region: 'Europe',
    operator: 'Eurail',
    description: 'Explore 33 countries with unlimited train travel across Europe',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3',
    validityDays: 60,
    travelDays: 15,
    price: 549,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited train travel', 'Flexible travel days', 'Free seat reservations on most trains'],
    countries: ['France', 'Germany', 'Italy', 'Spain', 'Switzerland', 'Austria', 'Netherlands', 'Belgium', 'and 25 more'],
    benefits: ['Free ferry crossings', 'Discounts on mountain railways', '10% off hotels'],
    restrictions: ['Must be activated before first use', 'Seat reservations may be required for high-speed trains'],
    rating: 4.7,
    reviewCount: 8542,
    popular: true,
  },
  {
    id: 'RP002',
    name: 'JR Pass (7 Days)',
    region: 'Japan',
    operator: 'JR Group',
    description: 'Unlimited travel on JR trains including Shinkansen bullet trains',
    imageUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0',
    validityDays: 7,
    travelDays: 7,
    price: 280,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited Shinkansen travel', 'JR local trains included', 'Airport transfers included'],
    countries: ['Japan'],
    benefits: ['Free luggage forwarding service', 'Discounts at JR hotels', 'Priority boarding on some trains'],
    restrictions: ['Not valid on Nozomi and Mizuho trains', 'Must be purchased before arriving in Japan'],
    rating: 4.9,
    reviewCount: 12350,
    popular: true,
  },
  {
    id: 'RP003',
    name: 'Swiss Travel Pass',
    region: 'Switzerland',
    operator: 'SBB',
    description: 'Unlimited travel on trains, buses, and boats throughout Switzerland',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7',
    validityDays: 8,
    travelDays: 8,
    price: 389,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited train, bus & boat travel', 'Free mountain excursions', 'Free museum entries'],
    countries: ['Switzerland', 'Liechtenstein'],
    benefits: ['50% off most mountain railways', 'Free entry to 500+ museums', 'Free public transport in 90+ cities'],
    restrictions: ['Seat reservations recommended for panoramic trains'],
    rating: 4.8,
    reviewCount: 5670,
    popular: true,
  },
  {
    id: 'RP004',
    name: 'Britrail England Pass',
    region: 'United Kingdom',
    operator: 'Britrail',
    description: 'Flexible train travel throughout England, Scotland, and Wales',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
    validityDays: 30,
    travelDays: 8,
    price: 325,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited travel on any 8 days', 'Valid on all train operators', 'No booking fees'],
    countries: ['England', 'Scotland', 'Wales'],
    benefits: ['Discounts on Eurostar to France', '2-for-1 entry at attractions', 'Free travel maps'],
    restrictions: ['Not valid in Northern Ireland', 'Reservations required on some routes'],
    rating: 4.5,
    reviewCount: 4230,
    popular: false,
  },
  {
    id: 'RP005',
    name: 'Interrail One Country Pass - Italy',
    region: 'Italy',
    operator: 'Interrail',
    description: 'Discover Italy by train with unlimited travel for EU residents',
    imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9',
    validityDays: 30,
    travelDays: 5,
    price: 189,
    currency: 'USD',
    ageCategory: 'youth',
    class: 'second',
    features: ['5 travel days in 1 month', 'All Italian trains included', 'Mobile pass available'],
    countries: ['Italy'],
    benefits: ['Ferry discounts to Sicily', '20% off private railways', 'Free city transport in some cities'],
    restrictions: ['Only for EU residents', 'Seat reservations required on Frecciarossa'],
    rating: 4.6,
    reviewCount: 3180,
    popular: false,
  },
  {
    id: 'RP006',
    name: 'Korea Rail Pass',
    region: 'South Korea',
    operator: 'Korail',
    description: 'Unlimited travel on KTX and all other Korail trains',
    imageUrl: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451',
    validityDays: 5,
    travelDays: 5,
    price: 165,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited KTX high-speed train', 'All regional trains included', 'Easy online reservation'],
    countries: ['South Korea'],
    benefits: ['Discounts on rail cruises', 'Free luggage delivery service', 'Tourism package discounts'],
    restrictions: ['Must be activated within 3 months of purchase'],
    rating: 4.7,
    reviewCount: 2890,
    popular: false,
  },
  {
    id: 'RP007',
    name: 'Eurail Select Pass - 4 Countries',
    region: 'Europe',
    operator: 'Eurail',
    description: 'Travel in 4 bordering European countries of your choice',
    imageUrl: 'https://images.unsplash.com/photo-1527838832700-5059252407fa',
    validityDays: 60,
    travelDays: 10,
    price: 425,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'first',
    features: ['Choose 4 bordering countries', '10 travel days in 2 months', 'First class comfort'],
    countries: ['Choose from 33 countries'],
    benefits: ['Free seat reservations', 'Lounge access', 'Complimentary travel guide'],
    restrictions: ['Countries must border each other', 'Reservations may be required'],
    rating: 4.6,
    reviewCount: 5120,
    popular: false,
  },
];

// Mock activities data
export const mockActivities: Activity[] = [
  {
    id: 'ACT001',
    name: 'Tokyo Skytree Observation Deck',
    description: 'Experience breathtaking 360° views of Tokyo from the tallest tower in Japan. Visit both the Tembo Deck (350m) and Tembo Galleria (450m) for unparalleled city vistas.',
    category: 'sightseeing',
    duration: 2,
    price: 28,
    rating: 4.7,
    location: {
      lat: 35.7101,
      lng: 139.8107,
      address: '1 Chome-1-2 Oshiage, Sumida City, Tokyo',
    },
  },
  {
    id: 'ACT002',
    name: 'Tsukiji Outer Market Food Tour',
    description: 'Join a guided walking tour through Tokyo\'s famous Tsukiji Outer Market. Sample fresh sushi, street food, and traditional Japanese delicacies while learning about culinary culture.',
    category: 'dining',
    duration: 3,
    price: 89,
    rating: 4.9,
    location: {
      lat: 35.6654,
      lng: 139.7707,
      address: 'Tsukiji, Chuo City, Tokyo',
    },
  },
  {
    id: 'ACT003',
    name: 'TeamLab Borderless Digital Art Museum',
    description: 'Immerse yourself in a world of interactive digital art installations. Walk through stunning light displays, flower gardens, and infinite crystal universes.',
    category: 'entertainment',
    duration: 2.5,
    price: 35,
    rating: 4.8,
    location: {
      lat: 35.6251,
      lng: 139.7754,
      address: 'Azabudai Hills, Minato City, Tokyo',
    },
  },
  {
    id: 'ACT004',
    name: 'Eiffel Tower Summit Access',
    description: 'Skip the line and ascend to the summit of Paris\'s iconic landmark. Enjoy champagne at the top while taking in panoramic views of the City of Light.',
    category: 'sightseeing',
    duration: 2,
    price: 42,
    rating: 4.6,
    location: {
      lat: 48.8584,
      lng: 2.2945,
      address: 'Champ de Mars, 5 Avenue Anatole France, Paris',
    },
  },
  {
    id: 'ACT005',
    name: 'Seine River Dinner Cruise',
    description: 'Glide along the Seine River on a luxury glass-enclosed boat. Savor a gourmet 3-course French dinner while passing illuminated landmarks like Notre-Dame and the Louvre.',
    category: 'dining',
    duration: 2.5,
    price: 125,
    rating: 4.7,
    location: {
      lat: 48.8606,
      lng: 2.3376,
      address: 'Port de la Bourdonnais, Paris',
    },
  },
  {
    id: 'ACT006',
    name: 'Louvre Museum Masterpieces Tour',
    description: 'Skip-the-line access with an expert guide who brings the world\'s most famous artworks to life, including the Mona Lisa, Venus de Milo, and Winged Victory.',
    category: 'sightseeing',
    duration: 3,
    price: 68,
    rating: 4.8,
    location: {
      lat: 48.8606,
      lng: 2.3376,
      address: 'Rue de Rivoli, Paris',
    },
  },
  {
    id: 'ACT007',
    name: 'Ubud Rice Terrace Swing & Waterfall Tour',
    description: 'Soar above lush rice terraces on famous jungle swings, visit sacred waterfalls, and explore traditional Balinese temples in this Instagram-worthy adventure.',
    category: 'adventure',
    duration: 8,
    price: 55,
    rating: 4.9,
    location: {
      lat: -8.5069,
      lng: 115.2625,
      address: 'Tegallalang, Ubud, Bali',
    },
  },
  {
    id: 'ACT008',
    name: 'Balinese Cooking Class & Market Tour',
    description: 'Visit a local market to select fresh ingredients, then learn to prepare authentic Balinese dishes in a traditional compound. Enjoy your creations for lunch.',
    category: 'dining',
    duration: 5,
    price: 45,
    rating: 4.8,
    location: {
      lat: -8.5095,
      lng: 115.2635,
      address: 'Ubud Traditional Market, Bali',
    },
  },
  {
    id: 'ACT009',
    name: 'Broadway Show: Hamilton',
    description: 'Experience the revolutionary Broadway musical that blends hip-hop, jazz, and R&B to tell the story of American founding father Alexander Hamilton.',
    category: 'entertainment',
    duration: 2.75,
    price: 189,
    rating: 4.9,
    location: {
      lat: 40.7590,
      lng: -73.9845,
      address: 'Richard Rodgers Theatre, 226 W 46th St, New York',
    },
  },
  {
    id: 'ACT010',
    name: 'Central Park Bike Tour',
    description: 'Pedal through 843 acres of NYC\'s urban oasis. See Bethesda Fountain, Strawberry Fields, the Lake, and hidden gems with a knowledgeable local guide.',
    category: 'adventure',
    duration: 2,
    price: 38,
    rating: 4.6,
    location: {
      lat: 40.7829,
      lng: -73.9654,
      address: 'Central Park, New York',
    },
  },
  {
    id: 'ACT011',
    name: 'Fifth Avenue Shopping Experience',
    description: 'Personal shopping guide for luxury flagship stores including Tiffany & Co., Saks Fifth Avenue, Bergdorf Goodman, and Apple Fifth Avenue.',
    category: 'shopping',
    duration: 4,
    price: 150,
    rating: 4.5,
    location: {
      lat: 40.7614,
      lng: -73.9776,
      address: 'Fifth Avenue, New York',
    },
  },
  {
    id: 'ACT012',
    name: 'Burj Khalifa At The Top Sky',
    description: 'Ascend to the 148th floor of the world\'s tallest building for exclusive access, luxury lounge refreshments, and unmatched Dubai skyline views.',
    category: 'sightseeing',
    duration: 1.5,
    price: 95,
    rating: 4.8,
    location: {
      lat: 25.1972,
      lng: 55.2744,
      address: '1 Sheikh Mohammed bin Rashid Blvd, Dubai',
    },
  },
  {
    id: 'ACT013',
    name: 'Desert Safari with BBQ Dinner',
    description: 'Thrilling dune bashing in 4x4 vehicles, camel riding, sandboarding, henna painting, and traditional Emirati BBQ dinner under the stars with belly dancing show.',
    category: 'adventure',
    duration: 6,
    price: 75,
    rating: 4.7,
    location: {
      lat: 24.9247,
      lng: 55.7656,
      address: 'Dubai Desert Conservation Reserve, Dubai',
    },
  },
  {
    id: 'ACT014',
    name: 'Dubai Mall & Gold Souk Shopping Tour',
    description: 'Explore the world\'s largest shopping mall with 1,200+ stores, then visit the traditional Gold Souk to bargain for jewelry with a local expert.',
    category: 'shopping',
    duration: 5,
    price: 60,
    rating: 4.4,
    location: {
      lat: 25.1972,
      lng: 55.2796,
      address: 'Dubai Mall, Downtown Dubai',
    },
  },
  {
    id: 'ACT015',
    name: 'Sagrada Familia Fast-Track & Guided Tour',
    description: 'Skip the queues to explore Gaudí\'s unfinished masterpiece with an expert guide. Marvel at the stunning stained glass, unique architecture, and intricate details.',
    category: 'sightseeing',
    duration: 1.5,
    price: 48,
    rating: 4.9,
    location: {
      lat: 41.4036,
      lng: 2.1744,
      address: 'C/ de Mallorca, 401, Barcelona',
    },
  },
  {
    id: 'ACT016',
    name: 'Barcelona Tapas & Wine Walking Tour',
    description: 'Discover Barcelona\'s culinary scene like a local. Visit 5 authentic tapas bars in Gothic Quarter and El Born, sampling regional wines and traditional dishes.',
    category: 'dining',
    duration: 3.5,
    price: 79,
    rating: 4.8,
    location: {
      lat: 41.3851,
      lng: 2.1734,
      address: 'Gothic Quarter, Barcelona',
    },
  },
  {
    id: 'ACT017',
    name: 'Park Güell Guided Tour',
    description: 'Explore Gaudí\'s whimsical park with mosaic salamander, undulating benches, and gingerbread-style houses overlooking Barcelona.',
    category: 'sightseeing',
    duration: 1.5,
    price: 32,
    rating: 4.6,
    location: {
      lat: 41.4145,
      lng: 2.1527,
      address: '08024 Barcelona, Spain',
    },
  },
  {
    id: 'ACT018',
    name: 'Gardens by the Bay Light Show',
    description: 'Witness the mesmerizing Garden Rhapsody light and music show at the iconic Supertree Grove. Includes access to Cloud Forest and Flower Dome.',
    category: 'entertainment',
    duration: 2.5,
    price: 35,
    rating: 4.7,
    location: {
      lat: 1.2816,
      lng: 103.8636,
      address: '18 Marina Gardens Dr, Singapore',
    },
  },
  {
    id: 'ACT019',
    name: 'Hawker Centre Food Adventure',
    description: 'Taste your way through Singapore\'s best hawker centers with a local foodie guide. Sample chicken rice, laksa, satay, and chili crab.',
    category: 'dining',
    duration: 3,
    price: 58,
    rating: 4.9,
    location: {
      lat: 1.2833,
      lng: 103.8442,
      address: 'Maxwell Food Centre, Singapore',
    },
  },
  {
    id: 'ACT020',
    name: 'British Museum Highlights Tour',
    description: 'Navigate one of the world\'s greatest museums with an expert guide. See the Rosetta Stone, Elgin Marbles, Egyptian mummies, and more.',
    category: 'sightseeing',
    duration: 2.5,
    price: 42,
    rating: 4.7,
    location: {
      lat: 51.5194,
      lng: -0.1270,
      address: 'Great Russell St, London',
    },
  },
  {
    id: 'ACT021',
    name: 'West End Theatre Show',
    description: 'Premium seats for London\'s best musicals and plays. Choose from The Phantom of the Opera, Les Misérables, or The Lion King.',
    category: 'entertainment',
    duration: 2.5,
    price: 95,
    rating: 4.8,
    location: {
      lat: 51.5110,
      lng: -0.1295,
      address: 'Theatre District, West End, London',
    },
  },
  {
    id: 'ACT022',
    name: 'Blue Lagoon Geothermal Spa',
    description: 'Relax in Iceland\'s world-famous milky-blue geothermal waters. Includes silica mud mask, complimentary drink, and access to saunas and steam rooms.',
    category: 'adventure',
    duration: 3,
    price: 95,
    rating: 4.6,
    location: {
      lat: 63.8804,
      lng: -22.4495,
      address: 'Norðurljósavegur 9, Grindavík, Iceland',
    },
  },
  {
    id: 'ACT023',
    name: 'Northern Lights Hunt',
    description: 'Chase the Aurora Borealis with expert guides who know the best viewing spots. Includes thermal clothing, hot drinks, and professional photography.',
    category: 'adventure',
    duration: 5,
    price: 125,
    rating: 4.7,
    location: {
      lat: 64.1466,
      lng: -21.9426,
      address: 'Reykjavik departure point, Iceland',
    },
  },
  {
    id: 'ACT024',
    name: 'Golden Circle Classic Tour',
    description: 'Visit Iceland\'s top three natural wonders: Þingvellir National Park, Geysir geothermal area, and the powerful Gullfoss waterfall.',
    category: 'sightseeing',
    duration: 8,
    price: 89,
    rating: 4.8,
    location: {
      lat: 64.3271,
      lng: -20.1201,
      address: 'Golden Circle Route, Iceland',
    },
  },
];

// Helper function to search trains
export const searchTrains = (origin?: string, destination?: string): Train[] => {
  return mockTrains.filter(train => {
    if (origin && !train.origin.toLowerCase().includes(origin.toLowerCase())) return false;
    if (destination && !train.destination.toLowerCase().includes(destination.toLowerCase())) return false;
    return true;
  });
};

// Helper function to search activities
export const searchActivities = (destination?: string, category?: string, maxPrice?: number): Activity[] => {
  return mockActivities.filter(activity => {
    if (destination && !activity.location.address.toLowerCase().includes(destination.toLowerCase())) return false;
    if (category && activity.category !== category) return false;
    if (maxPrice && activity.price > maxPrice) return false;
    return true;
  });
};

// Mock restaurants data
export const mockRestaurants: Restaurant[] = [
  {
    id: 'REST001',
    name: 'Sukiyabashi Jiro',
    cuisine: 'Japanese',
    address: 'Tsukamoto Sogyo Building, 2-15 Ginza 4-chome',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.9,
    reviewCount: 2850,
    priceLevel: 4,
    images: ['https://images.unsplash.com/photo-1579584425555-c3ce17fd4351'],
    description: 'World-renowned sushi restaurant with 3 Michelin stars. Experience the art of Edomae sushi by master chef Jiro Ono.',
    specialties: ['Omakase Sushi', 'Toro', 'Uni', 'Seasonal Fish'],
    amenities: ['Counter Seating', 'Reservations Required', 'No Photography'],
    openingHours: {
      Monday: '11:30-13:30, 17:30-20:30',
      Tuesday: '11:30-13:30, 17:30-20:30',
      Wednesday: '11:30-13:30, 17:30-20:30',
      Thursday: '11:30-13:30, 17:30-20:30',
      Friday: '11:30-13:30, 17:30-20:30',
      Saturday: 'Closed',
      Sunday: 'Closed',
    },
    acceptsReservations: true,
    mealPackages: [
      {
        id: 'PKG001',
        name: 'Omakase Experience',
        description: 'Chef\'s selection of 20 pieces of premium sushi',
        price: 450,
        items: ['20-piece sushi course', 'Miso soup', 'Green tea'],
        servings: 1,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        popular: true,
      },
    ],
    averageMealPrice: 450,
    location: { lat: 35.6714, lng: 139.7637 },
    tags: ['Michelin 3-Star', 'Sushi Master', 'Fine Dining', 'Reservation Required'],
  },
  {
    id: 'REST002',
    name: 'Ichiran Ramen Shibuya',
    cuisine: 'Japanese',
    address: '1-22-7 Jinnan, Shibuya',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.6,
    reviewCount: 8920,
    priceLevel: 1,
    images: ['https://images.unsplash.com/photo-1569718212165-3a8278d5f624'],
    description: 'Famous tonkotsu ramen chain with private booth seating. Customize your perfect bowl of ramen.',
    specialties: ['Tonkotsu Ramen', 'Extra Noodles', 'Soft-boiled Egg'],
    amenities: ['24/7 Open', 'Solo Dining Booths', 'English Menu', 'Quick Service'],
    openingHours: {
      Monday: '24 hours',
      Tuesday: '24 hours',
      Wednesday: '24 hours',
      Thursday: '24 hours',
      Friday: '24 hours',
      Saturday: '24 hours',
      Sunday: '24 hours',
    },
    acceptsReservations: false,
    mealPackages: [
      {
        id: 'PKG002',
        name: 'Ramen Lover Set',
        description: 'Classic tonkotsu ramen with premium toppings',
        price: 18,
        originalPrice: 25,
        items: ['Tonkotsu ramen', 'Extra chashu pork', 'Soft-boiled egg', 'Extra noodles'],
        servings: 1,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        popular: true,
      },
      {
        id: 'PKG003',
        name: 'Double Delight',
        description: 'Two bowls of ramen for sharing',
        price: 32,
        originalPrice: 40,
        items: ['2x Tonkotsu ramen', '2x Soft-boiled eggs', 'Gyoza (6 pieces)'],
        servings: 2,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      },
    ],
    averageMealPrice: 15,
    location: { lat: 35.6617, lng: 139.6984 },
    tags: ['Ramen', 'Quick Bite', 'Local Favorite', 'Budget-Friendly'],
  },
  {
    id: 'REST003',
    name: 'Le Jules Verne',
    cuisine: 'French',
    address: 'Eiffel Tower, 2nd Floor, Avenue Gustave Eiffel',
    city: 'Paris',
    country: 'France',
    rating: 4.7,
    reviewCount: 4230,
    priceLevel: 4,
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0'],
    description: 'Michelin-starred restaurant on the 2nd floor of the Eiffel Tower with breathtaking views of Paris.',
    specialties: ['Foie Gras', 'Beef Wellington', 'Lobster Thermidor', 'Soufflé'],
    amenities: ['Michelin Star', 'Panoramic Views', 'Fine Dining', 'Wine Pairing', 'Dress Code'],
    openingHours: {
      Monday: '12:00-13:30, 19:00-21:00',
      Tuesday: '12:00-13:30, 19:00-21:00',
      Wednesday: '12:00-13:30, 19:00-21:00',
      Thursday: '12:00-13:30, 19:00-21:00',
      Friday: '12:00-13:30, 19:00-21:00',
      Saturday: '12:00-13:30, 19:00-21:00',
      Sunday: '12:00-13:30, 19:00-21:00',
    },
    acceptsReservations: true,
    mealPackages: [
      {
        id: 'PKG004',
        name: 'Le Déjeuner (Lunch)',
        description: '3-course French lunch with wine',
        price: 125,
        originalPrice: 160,
        items: ['Appetizer', 'Main course', 'Dessert', 'Glass of wine'],
        servings: 1,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        validTime: 'Lunch only',
        popular: true,
      },
      {
        id: 'PKG005',
        name: 'Le Dîner Prestige',
        description: '7-course tasting menu with wine pairing',
        price: 295,
        items: ['7-course tasting menu', 'Wine pairing', 'Champagne welcome drink', 'Petit fours'],
        servings: 1,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        validTime: 'Dinner only',
        popular: true,
      },
    ],
    averageMealPrice: 200,
    location: { lat: 48.8584, lng: 2.2945 },
    tags: ['Michelin Star', 'Eiffel Tower View', 'Fine Dining', 'Romantic', 'Special Occasion'],
  },
  {
    id: 'REST004',
    name: 'L\'As du Fallafel',
    cuisine: 'Middle Eastern',
    address: '34 Rue des Rosiers, Le Marais',
    city: 'Paris',
    country: 'France',
    rating: 4.5,
    reviewCount: 12560,
    priceLevel: 1,
    images: ['https://images.unsplash.com/photo-1601050690597-df0568f70950'],
    description: 'Legendary falafel spot in the Marais district, famous for the best falafel in Paris.',
    specialties: ['Falafel Sandwich', 'Shawarma', 'Hummus', 'Fresh Juices'],
    amenities: ['Takeaway', 'Quick Service', 'Vegetarian Options', 'Halal'],
    openingHours: {
      Monday: '11:00-23:00',
      Tuesday: '11:00-23:00',
      Wednesday: '11:00-23:00',
      Thursday: '11:00-23:00',
      Friday: 'Closed',
      Saturday: 'Closed',
      Sunday: '11:00-23:00',
    },
    acceptsReservations: false,
    mealPackages: [
      {
        id: 'PKG006',
        name: 'Falafel Feast',
        description: 'Complete falafel meal for one',
        price: 15,
        originalPrice: 20,
        items: ['Falafel sandwich', 'Hummus plate', 'Fresh juice', 'Baklava'],
        servings: 1,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 12,
    location: { lat: 48.8576, lng: 2.3593 },
    tags: ['Street Food', 'Vegetarian', 'Local Legend', 'Budget-Friendly', 'Quick Bite'],
  },
  {
    id: 'REST005',
    name: 'Per Se',
    cuisine: 'American',
    address: 'Time Warner Center, 10 Columbus Circle',
    city: 'New York',
    country: 'USA',
    rating: 4.8,
    reviewCount: 3890,
    priceLevel: 4,
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4'],
    description: 'Thomas Keller\'s 3 Michelin star restaurant offering contemporary American cuisine with French influences.',
    specialties: ['Oysters and Pearls', 'Butter-Poached Lobster', 'Wagyu Beef', 'Chocolate Soufflé'],
    amenities: ['Michelin 3-Star', 'Central Park View', 'Wine Cellar', 'Private Dining'],
    openingHours: {
      Monday: 'Closed',
      Tuesday: '17:30-21:00',
      Wednesday: '17:30-21:00',
      Thursday: '17:30-21:00',
      Friday: '11:30-13:00, 17:30-21:00',
      Saturday: '11:30-13:00, 17:30-21:00',
      Sunday: '11:30-13:00, 17:30-21:00',
    },
    acceptsReservations: true,
    mealPackages: [
      {
        id: 'PKG007',
        name: 'Tasting Menu',
        description: '9-course chef\'s tasting menu',
        price: 375,
        items: ['9-course tasting menu', 'Amuse-bouche', 'Mignardises', 'Coffee or tea'],
        servings: 1,
        validDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 375,
    location: { lat: 40.7686, lng: -73.9830 },
    tags: ['Michelin 3-Star', 'Fine Dining', 'Special Occasion', 'Central Park View'],
  },
  {
    id: 'REST006',
    name: 'Joe\'s Pizza',
    cuisine: 'Italian',
    address: '7 Carmine St, Greenwich Village',
    city: 'New York',
    country: 'USA',
    rating: 4.4,
    reviewCount: 15840,
    priceLevel: 1,
    images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591'],
    description: 'Classic New York pizza joint serving legendary slices since 1975. Featured in Spider-Man 2!',
    specialties: ['Cheese Slice', 'Pepperoni Pizza', 'Sicilian Pizza'],
    amenities: ['Quick Service', 'Late Night', 'Takeaway', 'Cash Only'],
    openingHours: {
      Monday: '10:00-04:00',
      Tuesday: '10:00-04:00',
      Wednesday: '10:00-04:00',
      Thursday: '10:00-04:00',
      Friday: '10:00-05:00',
      Saturday: '10:00-05:00',
      Sunday: '10:00-04:00',
    },
    acceptsReservations: false,
    mealPackages: [
      {
        id: 'PKG008',
        name: 'Pizza Party Pack',
        description: 'Two large pizzas for sharing',
        price: 45,
        originalPrice: 55,
        items: ['2 large pizzas', 'Your choice of toppings', 'Garlic knots', '2L soda'],
        servings: 4,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 15,
    location: { lat: 40.7305, lng: -74.0026 },
    tags: ['Pizza', 'NYC Icon', 'Budget-Friendly', 'Quick Bite', 'Late Night'],
  },
  {
    id: 'REST007',
    name: 'Nusr-Et Steakhouse',
    cuisine: 'Turkish',
    address: 'Jumeirah Emirates Towers',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.3,
    reviewCount: 5670,
    priceLevel: 4,
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947'],
    description: 'Celebrity chef Salt Bae\'s famous steakhouse offering premium cuts and theatrical dining.',
    specialties: ['Tomahawk Steak', 'Golden Burger', 'Ottoman Steak', 'Baklava'],
    amenities: ['Celebrity Chef', 'Theatrical Service', 'Premium Meats', 'Instagram-Worthy'],
    openingHours: {
      Monday: '12:00-01:00',
      Tuesday: '12:00-01:00',
      Wednesday: '12:00-01:00',
      Thursday: '12:00-02:00',
      Friday: '12:00-02:00',
      Saturday: '12:00-02:00',
      Sunday: '12:00-01:00',
    },
    acceptsReservations: true,
    mealPackages: [
      {
        id: 'PKG009',
        name: 'Meat Lover\'s Feast',
        description: 'Premium steak experience for two',
        price: 350,
        originalPrice: 420,
        items: ['2x Wagyu steaks', 'Sides selection', 'Dessert', 'Signature salt sprinkling'],
        servings: 2,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 200,
    location: { lat: 25.2177, lng: 55.2812 },
    tags: ['Steakhouse', 'Celebrity Chef', 'Luxury', 'Instagram-Worthy', 'Fine Dining'],
  },
  {
    id: 'REST008',
    name: 'Ravi Restaurant',
    cuisine: 'Pakistani',
    address: 'Satwa, near Rydges Plaza Hotel',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.5,
    reviewCount: 18920,
    priceLevel: 1,
    images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe'],
    description: 'Legendary Pakistani restaurant serving authentic curries and grilled meats since 1978.',
    specialties: ['Chicken Tikka', 'Mutton Karahi', 'Biryani', 'Naan'],
    amenities: ['24/7 Open', 'Family-Friendly', 'Halal', 'Outdoor Seating'],
    openingHours: {
      Monday: '24 hours',
      Tuesday: '24 hours',
      Wednesday: '24 hours',
      Thursday: '24 hours',
      Friday: '24 hours',
      Saturday: '24 hours',
      Sunday: '24 hours',
    },
    acceptsReservations: false,
    mealPackages: [
      {
        id: 'PKG010',
        name: 'Family Feast',
        description: 'Complete Pakistani meal for 4',
        price: 65,
        originalPrice: 85,
        items: ['Mixed grill platter', 'Chicken karahi', 'Mutton biryani', 'Naan basket', 'Raita', 'Salad', 'Kheer dessert'],
        servings: 4,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 20,
    location: { lat: 25.2309, lng: 55.2868 },
    tags: ['Pakistani', 'Local Legend', 'Budget-Friendly', '24/7', 'Family-Friendly'],
  },
  {
    id: 'REST009',
    name: 'Tickets Bar',
    cuisine: 'Spanish',
    address: 'Avinguda del Paral·lel, 164',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.8,
    reviewCount: 6230,
    priceLevel: 3,
    images: ['https://images.unsplash.com/photo-1555939594-58d7cb561ad1'],
    description: 'Avant-garde tapas bar by the Adrià brothers. Experience molecular gastronomy in a casual setting.',
    specialties: ['Liquid Olives', 'Air Baguette', 'Oyster & Passion Fruit', 'Iberian Ham'],
    amenities: ['Michelin Star', 'Molecular Gastronomy', 'Creative Tapas', 'Bar Seating'],
    openingHours: {
      Monday: 'Closed',
      Tuesday: '19:00-23:00',
      Wednesday: '19:00-23:00',
      Thursday: '19:00-23:00',
      Friday: '19:00-23:30',
      Saturday: '19:00-23:30',
      Sunday: 'Closed',
    },
    acceptsReservations: true,
    mealPackages: [
      {
        id: 'PKG011',
        name: 'Tapas Tasting Journey',
        description: 'Creative tapas experience',
        price: 85,
        items: ['12 creative tapas', 'Bread selection', 'Olive oil tasting', 'Dessert'],
        servings: 1,
        validDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        popular: true,
      },
    ],
    averageMealPrice: 75,
    location: { lat: 41.3747, lng: 2.1623 },
    tags: ['Michelin Star', 'Molecular Gastronomy', 'Tapas', 'Innovative', 'Reservation Required'],
  },
  {
    id: 'REST010',
    name: 'Cervecería Catalana',
    cuisine: 'Spanish',
    address: 'Carrer de Mallorca, 236',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.6,
    reviewCount: 14520,
    priceLevel: 2,
    images: ['https://images.unsplash.com/photo-1534422298391-e4f8c172dddb'],
    description: 'Bustling tapas bar with an incredible variety of pintxos and traditional Spanish dishes.',
    specialties: ['Jamón Ibérico', 'Patatas Bravas', 'Croquetas', 'Pulpo a la Gallega'],
    amenities: ['Traditional Tapas', 'Bar Seating', 'Wine Selection', 'Outdoor Terrace'],
    openingHours: {
      Monday: '08:00-01:30',
      Tuesday: '08:00-01:30',
      Wednesday: '08:00-01:30',
      Thursday: '08:00-01:30',
      Friday: '08:00-02:00',
      Saturday: '09:00-02:00',
      Sunday: '09:00-01:30',
    },
    acceptsReservations: false,
    mealPackages: [
      {
        id: 'PKG012',
        name: 'Tapas for Two',
        description: 'Selection of classic tapas',
        price: 45,
        originalPrice: 60,
        items: ['8 tapas selection', 'Bread and aioli', 'Sangria pitcher', 'Crema catalana'],
        servings: 2,
        validDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        popular: true,
      },
    ],
    averageMealPrice: 30,
    location: { lat: 41.3912, lng: 2.1616 },
    tags: ['Tapas', 'Local Favorite', 'Wine Bar', 'Bustling', 'Traditional'],
  },
];

// Helper function to search restaurants
export const searchRestaurants = (city?: string, cuisine?: string, maxPriceLevel?: number): Restaurant[] => {
  return mockRestaurants.filter(restaurant => {
    if (city && !restaurant.city.toLowerCase().includes(city.toLowerCase())) return false;
    if (cuisine && restaurant.cuisine.toLowerCase() !== cuisine.toLowerCase()) return false;
    if (maxPriceLevel && restaurant.priceLevel > maxPriceLevel) return false;
    return true;
  });
};
