import { Flight, Hotel, Destination, PriceTrend, Train, RailPass } from '@/types';

// Mock flight data
export const mockFlights: Flight[] = [
  {
    id: 'FL001',
    airline: 'United Airlines',
    flightNumber: 'UA889',
    origin: 'SFO',
    destination: 'NRT',
    departure: new Date('2025-12-15T10:30:00'),
    arrival: new Date('2025-12-16T14:45:00'),
    duration: 675,
    price: 850,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.2,
    onTimePerformance: 82,
    carbonEmission: 920,
  },
  {
    id: 'FL002',
    airline: 'ANA',
    flightNumber: 'NH7',
    origin: 'SFO',
    destination: 'NRT',
    departure: new Date('2025-12-15T11:00:00'),
    arrival: new Date('2025-12-16T15:30:00'),
    duration: 690,
    price: 920,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.5,
    onTimePerformance: 89,
    carbonEmission: 900,
  },
  {
    id: 'FL003',
    airline: 'Delta',
    flightNumber: 'DL283',
    origin: 'LAX',
    destination: 'CDG',
    departure: new Date('2025-12-20T18:00:00'),
    arrival: new Date('2025-12-21T14:30:00'),
    duration: 630,
    price: 1200,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.3,
    onTimePerformance: 85,
    carbonEmission: 1050,
  },
  {
    id: 'FL004',
    airline: 'Emirates',
    flightNumber: 'EK215',
    origin: 'JFK',
    destination: 'DXB',
    departure: new Date('2025-12-18T22:30:00'),
    arrival: new Date('2025-12-19T19:45:00'),
    duration: 795,
    price: 1450,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.8,
    onTimePerformance: 91,
    carbonEmission: 1200,
  },
  {
    id: 'FL005',
    airline: 'Singapore Airlines',
    flightNumber: 'SQ12',
    origin: 'LAX',
    destination: 'SIN',
    departure: new Date('2025-12-22T00:30:00'),
    arrival: new Date('2025-12-23T07:15:00'),
    duration: 945,
    price: 1350,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.9,
    onTimePerformance: 92,
    carbonEmission: 1400,
  },
  {
    id: 'FL006',
    airline: 'British Airways',
    flightNumber: 'BA283',
    origin: 'JFK',
    destination: 'LHR',
    departure: new Date('2025-12-16T21:00:00'),
    arrival: new Date('2025-12-17T09:30:00'),
    duration: 450,
    price: 950,
    currency: 'USD',
    stops: 0,
    cabinClass: 'premium-economy',
    rating: 4.1,
    onTimePerformance: 79,
    carbonEmission: 850,
  },
  {
    id: 'FL007',
    airline: 'Lufthansa',
    flightNumber: 'LH400',
    origin: 'JFK',
    destination: 'FRA',
    departure: new Date('2025-12-19T17:45:00'),
    arrival: new Date('2025-12-20T07:20:00'),
    duration: 455,
    price: 880,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    rating: 4.3,
    onTimePerformance: 86,
    carbonEmission: 870,
  },
  {
    id: 'FL008',
    airline: 'Qatar Airways',
    flightNumber: 'QR701',
    origin: 'LAX',
    destination: 'DOH',
    departure: new Date('2025-12-21T15:20:00'),
    arrival: new Date('2025-12-22T21:30:00'),
    duration: 850,
    price: 1280,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    rating: 4.7,
    onTimePerformance: 88,
    carbonEmission: 1300,
  },
];

// Mock hotel data
export const mockHotels: Hotel[] = [
  {
    id: 'HT001',
    name: 'Grand Hyatt Tokyo',
    address: '6-10-3 Roppongi, Minato-ku',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.5,
    stars: 5,
    price: 280,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Room Service'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa'],
    distanceToCenter: 2.5,
    reviewScore: 8.9,
    reviewCount: 3420,
  },
  {
    id: 'HT002',
    name: 'Hotel Gracery Shinjuku',
    address: '1-19-1 Kabukicho, Shinjuku-ku',
    city: 'Tokyo',
    country: 'Japan',
    rating: 4.2,
    stars: 4,
    price: 180,
    currency: 'USD',
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    distanceToCenter: 1.2,
    reviewScore: 8.5,
    reviewCount: 2156,
  },
  {
    id: 'HT003',
    name: 'Hôtel Plaza Athénée',
    address: '25 Avenue Montaigne',
    city: 'Paris',
    country: 'France',
    rating: 4.8,
    stars: 5,
    price: 950,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Butler Service', 'Michelin Restaurant'],
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb'],
    distanceToCenter: 0.8,
    reviewScore: 9.4,
    reviewCount: 1876,
  },
  {
    id: 'HT004',
    name: 'Generator Paris',
    address: '9-11 Place du Colonel Fabien',
    city: 'Paris',
    country: 'France',
    rating: 3.9,
    stars: 3,
    price: 85,
    currency: 'USD',
    amenities: ['WiFi', 'Bar', 'Terrace', 'Lounge'],
    images: ['https://images.unsplash.com/photo-1455587734955-081b22074882'],
    distanceToCenter: 3.5,
    reviewScore: 7.8,
    reviewCount: 892,
  },
  {
    id: 'HT005',
    name: 'Marina Bay Sands',
    address: '10 Bayfront Avenue',
    city: 'Singapore',
    country: 'Singapore',
    rating: 4.7,
    stars: 5,
    price: 420,
    currency: 'USD',
    amenities: ['WiFi', 'Infinity Pool', 'Casino', 'Gym', 'Spa', 'Shopping Mall', 'Rooftop Bar'],
    images: ['https://images.unsplash.com/photo-1525438160292-a4a860951216'],
    distanceToCenter: 1.5,
    reviewScore: 9.1,
    reviewCount: 5230,
  },
  {
    id: 'HT006',
    name: 'The Ritz-Carlton New York',
    address: 'Central Park, 50 Central Park South',
    city: 'New York',
    country: 'USA',
    rating: 4.8,
    stars: 5,
    price: 650,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa', 'Concierge', 'Central Park View'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945'],
    distanceToCenter: 0.5,
    reviewScore: 9.3,
    reviewCount: 4120,
  },
  {
    id: 'HT007',
    name: 'Burj Al Arab',
    address: 'Jumeirah Beach Road',
    city: 'Dubai',
    country: 'UAE',
    rating: 5.0,
    stars: 5,
    price: 1500,
    currency: 'USD',
    amenities: ['WiFi', 'Private Beach', 'Butler Service', 'Helipad', 'Spa', 'Fine Dining', 'Gold Plated Fixtures'],
    images: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c'],
    distanceToCenter: 8.0,
    reviewScore: 9.7,
    reviewCount: 6890,
  },
  {
    id: 'HT008',
    name: 'W Barcelona',
    address: 'Placa de la Rosa dels Vents 1',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.5,
    stars: 5,
    price: 320,
    currency: 'USD',
    amenities: ['WiFi', 'Beachfront', 'Pool', 'Gym', 'Restaurant', 'Nightclub', 'Spa'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'],
    distanceToCenter: 3.2,
    reviewScore: 8.8,
    reviewCount: 3456,
  },
];

// Mock destination data
export const mockDestinations: Destination[] = [
  {
    id: 'DEST001',
    name: 'Tokyo',
    country: 'Japan',
    description: 'A vibrant metropolis blending traditional culture with cutting-edge technology',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf',
    popularityScore: 9.5,
    averageTemperature: 16,
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
  },
  {
    id: 'DEST002',
    name: 'Paris',
    country: 'France',
    description: 'The City of Light, famous for art, fashion, gastronomy, and culture',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34',
    popularityScore: 9.7,
    averageTemperature: 12,
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST003',
    name: 'Bali',
    country: 'Indonesia',
    description: 'Tropical paradise with stunning beaches, rice terraces, and spiritual culture',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
    popularityScore: 9.2,
    averageTemperature: 27,
    bestMonths: ['April', 'May', 'June', 'July', 'August', 'September'],
  },
  {
    id: 'DEST004',
    name: 'New York',
    country: 'USA',
    description: 'The city that never sleeps, offering world-class dining, shopping, and entertainment',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9',
    popularityScore: 9.6,
    averageTemperature: 13,
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST005',
    name: 'Dubai',
    country: 'UAE',
    description: 'Futuristic city with luxury shopping, ultramodern architecture, and desert adventures',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
    popularityScore: 9.0,
    averageTemperature: 27,
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
  },
  {
    id: 'DEST006',
    name: 'Barcelona',
    country: 'Spain',
    description: 'Mediterranean gem with stunning architecture, beaches, and vibrant culture',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded',
    popularityScore: 9.3,
    averageTemperature: 16,
    bestMonths: ['May', 'June', 'September', 'October'],
  },
  {
    id: 'DEST007',
    name: 'Singapore',
    country: 'Singapore',
    description: 'Modern city-state with futuristic gardens, diverse cuisine, and world-class shopping',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
    popularityScore: 9.4,
    averageTemperature: 28,
    bestMonths: ['February', 'March', 'April', 'July', 'August'],
  },
  {
    id: 'DEST008',
    name: 'London',
    country: 'United Kingdom',
    description: 'Historic capital with royal palaces, world-class museums, and multicultural neighborhoods',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
    popularityScore: 9.5,
    averageTemperature: 11,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
  },
  {
    id: 'DEST009',
    name: 'Iceland',
    country: 'Iceland',
    description: 'Land of fire and ice with stunning waterfalls, glaciers, and Northern Lights',
    imageUrl: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927',
    popularityScore: 8.9,
    averageTemperature: 5,
    bestMonths: ['June', 'July', 'August', 'September'],
  },
];

// Mock price trend data generator
export const generatePriceTrend = (basePrice: number, days: number = 30): PriceTrend[] => {
  const trends: PriceTrend[] = [];
  const today = new Date();

  for (let i = -days; i <= 30; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() + i);

    // Create realistic price fluctuation
    const variance = Math.sin(i / 7) * 100 + Math.random() * 80;
    const price = Math.round(basePrice + variance);

    trends.push({
      date: date.toISOString().split('T')[0],
      price,
      prediction: i > 0,
    });
  }

  return trends;
};

// Helper function to search flights
export const searchFlights = (origin?: string, destination?: string): Flight[] => {
  return mockFlights.filter(flight => {
    if (origin && !flight.origin.toLowerCase().includes(origin.toLowerCase())) return false;
    if (destination && !flight.destination.toLowerCase().includes(destination.toLowerCase())) return false;
    return true;
  });
};

// Helper function to search hotels
export const searchHotels = (city?: string, maxPrice?: number): Hotel[] => {
  return mockHotels.filter(hotel => {
    if (city && !hotel.city.toLowerCase().includes(city.toLowerCase())) return false;
    if (maxPrice && hotel.price > maxPrice) return false;
    return true;
  });
};

// Mock train data
export const mockTrains: Train[] = [
  {
    id: 'TR001',
    operator: 'JR East',
    trainNumber: 'Nozomi 1',
    trainType: 'Shinkansen (Bullet Train)',
    origin: 'Tokyo',
    destination: 'Osaka',
    departure: new Date('2025-12-15T09:00:00'),
    arrival: new Date('2025-12-15T11:30:00'),
    duration: 150,
    price: 135,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Vending Machines', 'Spacious Seats'],
    seatAvailability: { window: 12, aisle: 8, total: 20 },
    rating: 4.9,
    onTimePerformance: 99,
    carbonEmission: 18,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR002',
    operator: 'SNCF',
    trainNumber: 'TGV 6821',
    trainType: 'TGV (High Speed)',
    origin: 'Paris',
    destination: 'Lyon',
    departure: new Date('2025-12-16T07:30:00'),
    arrival: new Date('2025-12-16T09:28:00'),
    duration: 118,
    price: 65,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Café Car', 'Air Conditioning'],
    seatAvailability: { window: 15, aisle: 10, total: 25 },
    rating: 4.6,
    onTimePerformance: 88,
    carbonEmission: 14,
    flexibleTicket: false,
    refundable: false,
  },
  {
    id: 'TR003',
    operator: 'DB (Deutsche Bahn)',
    trainNumber: 'ICE 71',
    trainType: 'ICE (InterCity Express)',
    origin: 'Berlin',
    destination: 'Munich',
    departure: new Date('2025-12-17T10:15:00'),
    arrival: new Date('2025-12-17T14:30:00'),
    duration: 255,
    price: 89,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Restaurant Car', 'Quiet Zone', 'Reclining Seats'],
    seatAvailability: { window: 8, aisle: 5, total: 13 },
    rating: 4.7,
    onTimePerformance: 82,
    carbonEmission: 22,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR004',
    operator: 'Trenitalia',
    trainNumber: 'Frecciarossa 9320',
    trainType: 'Frecciarossa (Red Arrow)',
    origin: 'Rome',
    destination: 'Milan',
    departure: new Date('2025-12-18T14:00:00'),
    arrival: new Date('2025-12-18T17:10:00'),
    duration: 190,
    price: 75,
    currency: 'USD',
    class: 'business',
    amenities: ['WiFi', 'Power Outlets', 'Complimentary Snacks', 'Extra Legroom'],
    seatAvailability: { window: 6, aisle: 4, total: 10 },
    rating: 4.5,
    onTimePerformance: 85,
    carbonEmission: 16,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR005',
    operator: 'Renfe',
    trainNumber: 'AVE 03050',
    trainType: 'AVE (Alta Velocidad Española)',
    origin: 'Madrid',
    destination: 'Barcelona',
    departure: new Date('2025-12-19T08:00:00'),
    arrival: new Date('2025-12-19T10:45:00'),
    duration: 165,
    price: 68,
    currency: 'USD',
    class: 'standard',
    amenities: ['WiFi', 'Power Outlets', 'Snack Service'],
    seatAvailability: { window: 18, aisle: 12, total: 30 },
    rating: 4.4,
    onTimePerformance: 90,
    carbonEmission: 15,
    flexibleTicket: false,
    refundable: false,
  },
  {
    id: 'TR006',
    operator: 'SBB',
    trainNumber: 'IC 715',
    trainType: 'InterCity',
    origin: 'Zurich',
    destination: 'Geneva',
    departure: new Date('2025-12-20T11:30:00'),
    arrival: new Date('2025-12-20T14:25:00'),
    duration: 175,
    price: 95,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Dining Car', 'Panoramic Windows'],
    seatAvailability: { window: 10, aisle: 6, total: 16 },
    rating: 4.8,
    onTimePerformance: 95,
    carbonEmission: 12,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR007',
    operator: 'Amtrak',
    trainNumber: 'Acela 2150',
    trainType: 'Acela Express',
    origin: 'New York',
    destination: 'Washington DC',
    departure: new Date('2025-12-21T15:00:00'),
    arrival: new Date('2025-12-21T18:00:00'),
    duration: 180,
    price: 125,
    currency: 'USD',
    class: 'business',
    amenities: ['WiFi', 'Power Outlets', 'Café Car', 'Conference Tables'],
    seatAvailability: { window: 14, aisle: 9, total: 23 },
    rating: 4.2,
    onTimePerformance: 78,
    carbonEmission: 25,
    flexibleTicket: true,
    refundable: true,
  },
  {
    id: 'TR008',
    operator: 'JR West',
    trainNumber: 'Hikari 522',
    trainType: 'Shinkansen',
    origin: 'Kyoto',
    destination: 'Hiroshima',
    departure: new Date('2025-12-22T12:00:00'),
    arrival: new Date('2025-12-22T13:48:00'),
    duration: 108,
    price: 115,
    currency: 'USD',
    class: 'first',
    amenities: ['WiFi', 'Power Outlets', 'Extra Wide Seats', 'Luggage Space'],
    seatAvailability: { window: 7, aisle: 5, total: 12 },
    rating: 4.9,
    onTimePerformance: 98,
    carbonEmission: 15,
    flexibleTicket: true,
    refundable: true,
  },
];

// Mock rail pass data
export const mockRailPasses: RailPass[] = [
  {
    id: 'RP001',
    name: 'Eurail Global Pass',
    region: 'Europe',
    operator: 'Eurail',
    description: 'Explore 33 countries with unlimited train travel across Europe',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3',
    validityDays: 60,
    travelDays: 15,
    price: 549,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited train travel', 'Flexible travel days', 'Free seat reservations on most trains'],
    countries: ['France', 'Germany', 'Italy', 'Spain', 'Switzerland', 'Austria', 'Netherlands', 'Belgium', 'and 25 more'],
    benefits: ['Free ferry crossings', 'Discounts on mountain railways', '10% off hotels'],
    restrictions: ['Must be activated before first use', 'Seat reservations may be required for high-speed trains'],
    rating: 4.7,
    reviewCount: 8542,
    popular: true,
  },
  {
    id: 'RP002',
    name: 'JR Pass (7 Days)',
    region: 'Japan',
    operator: 'JR Group',
    description: 'Unlimited travel on JR trains including Shinkansen bullet trains',
    imageUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0',
    validityDays: 7,
    travelDays: 7,
    price: 280,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited Shinkansen travel', 'JR local trains included', 'Airport transfers included'],
    countries: ['Japan'],
    benefits: ['Free luggage forwarding service', 'Discounts at JR hotels', 'Priority boarding on some trains'],
    restrictions: ['Not valid on Nozomi and Mizuho trains', 'Must be purchased before arriving in Japan'],
    rating: 4.9,
    reviewCount: 12350,
    popular: true,
  },
  {
    id: 'RP003',
    name: 'Swiss Travel Pass',
    region: 'Switzerland',
    operator: 'SBB',
    description: 'Unlimited travel on trains, buses, and boats throughout Switzerland',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7',
    validityDays: 8,
    travelDays: 8,
    price: 389,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited train, bus & boat travel', 'Free mountain excursions', 'Free museum entries'],
    countries: ['Switzerland', 'Liechtenstein'],
    benefits: ['50% off most mountain railways', 'Free entry to 500+ museums', 'Free public transport in 90+ cities'],
    restrictions: ['Seat reservations recommended for panoramic trains'],
    rating: 4.8,
    reviewCount: 5670,
    popular: true,
  },
  {
    id: 'RP004',
    name: 'Britrail England Pass',
    region: 'United Kingdom',
    operator: 'Britrail',
    description: 'Flexible train travel throughout England, Scotland, and Wales',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
    validityDays: 30,
    travelDays: 8,
    price: 325,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited travel on any 8 days', 'Valid on all train operators', 'No booking fees'],
    countries: ['England', 'Scotland', 'Wales'],
    benefits: ['Discounts on Eurostar to France', '2-for-1 entry at attractions', 'Free travel maps'],
    restrictions: ['Not valid in Northern Ireland', 'Reservations required on some routes'],
    rating: 4.5,
    reviewCount: 4230,
    popular: false,
  },
  {
    id: 'RP005',
    name: 'Interrail One Country Pass - Italy',
    region: 'Italy',
    operator: 'Interrail',
    description: 'Discover Italy by train with unlimited travel for EU residents',
    imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9',
    validityDays: 30,
    travelDays: 5,
    price: 189,
    currency: 'USD',
    ageCategory: 'youth',
    class: 'second',
    features: ['5 travel days in 1 month', 'All Italian trains included', 'Mobile pass available'],
    countries: ['Italy'],
    benefits: ['Ferry discounts to Sicily', '20% off private railways', 'Free city transport in some cities'],
    restrictions: ['Only for EU residents', 'Seat reservations required on Frecciarossa'],
    rating: 4.6,
    reviewCount: 3180,
    popular: false,
  },
  {
    id: 'RP006',
    name: 'Korea Rail Pass',
    region: 'South Korea',
    operator: 'Korail',
    description: 'Unlimited travel on KTX and all other Korail trains',
    imageUrl: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451',
    validityDays: 5,
    travelDays: 5,
    price: 165,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'second',
    features: ['Unlimited KTX high-speed train', 'All regional trains included', 'Easy online reservation'],
    countries: ['South Korea'],
    benefits: ['Discounts on rail cruises', 'Free luggage delivery service', 'Tourism package discounts'],
    restrictions: ['Must be activated within 3 months of purchase'],
    rating: 4.7,
    reviewCount: 2890,
    popular: false,
  },
  {
    id: 'RP007',
    name: 'Eurail Select Pass - 4 Countries',
    region: 'Europe',
    operator: 'Eurail',
    description: 'Travel in 4 bordering European countries of your choice',
    imageUrl: 'https://images.unsplash.com/photo-1527838832700-5059252407fa',
    validityDays: 60,
    travelDays: 10,
    price: 425,
    currency: 'USD',
    ageCategory: 'adult',
    class: 'first',
    features: ['Choose 4 bordering countries', '10 travel days in 2 months', 'First class comfort'],
    countries: ['Choose from 33 countries'],
    benefits: ['Free seat reservations', 'Lounge access', 'Complimentary travel guide'],
    restrictions: ['Countries must border each other', 'Reservations may be required'],
    rating: 4.6,
    reviewCount: 5120,
    popular: false,
  },
];

// Helper function to search trains
export const searchTrains = (origin?: string, destination?: string): Train[] => {
  return mockTrains.filter(train => {
    if (origin && !train.origin.toLowerCase().includes(origin.toLowerCase())) return false;
    if (destination && !train.destination.toLowerCase().includes(destination.toLowerCase())) return false;
    return true;
  });
};
